# -*- coding: utf-8 -*-
"""Zomato Review Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d75D8eEa-FkyieJsMU1lzuSTBm9K3Uiu

NLP

Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing Dataset"""

dataset = pd.read_csv('Zomato Review Kaggle.tsv' , delimiter = '\t' , quoting = 3 , encoding = 'latin-1')

"""Cleaning the Dataset"""

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []
for i in range(0, 1000):
  zomato_ratings = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
  zomato_ratings = zomato_ratings.lower()
  zomato_ratings = zomato_ratings.split()

  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')

  all_stopwords.remove('not')
  zomato_ratings = [ps.stem(word) for word in zomato_ratings if word not in all_stopwords]
  zomato_ratings = ' '.join(zomato_ratings)
  corpus.append(zomato_ratings)

print(corpus)

"""Bag of Words Creation"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1600)
X = cv.fit_transform(corpus).toarray()
import numpy as np

corpus = []
labels = []

for i in range(len(dataset)):
    review = str(dataset.iloc[i, 0])      # review text
    label  = dataset.iloc[i, -1]          # sentiment / target

    if review.strip() != "" and not pd.isna(label):
        corpus.append(review)
        labels.append(label)

X = cv.fit_transform(corpus).toarray()
y = np.array(labels)

print(X.shape)
print(y.shape)
print(np.isnan(y).sum())   # must be 0

"""# Splitting data into test and training sets

"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 21)

"""Training Naive Bayes"""

from sklearn.naive_bayes import GaussianNB
Classifier = GaussianNB()
Classifier.fit(X_train, y_train )

"""Prediction on the test set"""

y_pred = Classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

"""Making Confusion Matrix"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

"""Visualization(Matplotlib)"""

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

review_length = dataset['Review'].astype(str).apply(len)

plt.hist(review_length, bins=50)
plt.xlabel("Review Length")
plt.ylabel("Frequency")
plt.title("Distribution of Review Lengths")
plt.show()

"""b) Positive vs Negative Review"""

plt.figure(figsize=(6,4))
dataset.iloc[:, -1].value_counts().plot(
    kind='bar',
    edgecolor='black'
)

plt.xticks([0,1], ['Negative', 'Positive'], rotation=0)
plt.title("Sentiment Distribution of Zomato Reviews", fontsize=13)
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.tight_layout()
plt.show()

"""c) Confusion matrix using seaborn"""

import seaborn as sns

sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()